name: Deploy Laravel to Azure App Service

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql
        
    - name: Copy .env.example to .env
      run: cp .env.example .env
      
    - name: Install Composer dependencies
      run: composer install --optimize-autoloader --no-dev
      
    - name: Generate application key
      run: php artisan key:generate
      
    - name: Set directory permissions
      run: chmod -R 775 storage bootstrap/cache
      
    - name: Create production .env
      run: |
        echo "APP_NAME=LuaranApp" > .env
        echo "APP_ENV=production" >> .env
        echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "APP_URL=https://luaranapp-b6ftembfh3hae0hs.canadacentral-01.azurewebsites.net" >> .env
        echo "APP_LOCALE=en" >> .env
        echo "APP_FALLBACK_LOCALE=en" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "SESSION_DRIVER=database" >> .env
        echo "CACHE_STORE=database" >> .env
        echo "QUEUE_CONNECTION=database" >> .env
        echo "LOG_CHANNEL=stack" >> .env
        echo "LOG_LEVEL=error" >> .env
        echo "BCRYPT_ROUNDS=12" >> .env
        
    - name: Generate fresh application key
      run: php artisan key:generate
      
    - name: Optimize Laravel for production
      run: |
        php artisan config:cache
        php artisan view:cache
        # Skip route:cache if you have route issues
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'luaranapp-b6ftembfh3hae0hs'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
