# Laravel deployment to Azure Web App
name: Deploy Laravel to Azure Web App - Jokotingkir

on:
  push:
    branches: [ main, master ]  # Support both main and master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test --without-tty

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: php-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: php-app

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Production Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Create .env file for production
      run: |
        echo "APP_NAME=Jokotingkir" > .env
        echo "APP_ENV=production" >> .env
        echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "APP_URL=https://jokotingkir-dshcagcgb4fnb2dw.canadacentral-01.azurewebsites.net" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=\${AZURE_MYSQL_HOST}" >> .env
        echo "DB_PORT=\${AZURE_MYSQL_PORT}" >> .env
        echo "DB_DATABASE=\${AZURE_MYSQL_DBNAME}" >> .env
        echo "DB_USERNAME=\${AZURE_MYSQL_USERNAME}" >> .env
        echo "DB_PASSWORD=\${AZURE_MYSQL_PASSWORD}" >> .env
        echo "SESSION_DRIVER=database" >> .env
        echo "CACHE_STORE=database" >> .env
        echo "QUEUE_CONNECTION=database" >> .env
        echo "LOG_CHANNEL=stack" >> .env
        echo "LOG_LEVEL=error" >> .env
        echo "APP_LOCALE=en" >> .env
        echo "APP_FALLBACK_LOCALE=en" >> .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Clear Laravel Cache
      run: |
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
        php artisan cache:clear

    - name: Optimize Laravel (without route cache)
      run: |
        php artisan config:cache
        # php artisan route:cache  # Disabled temporarily due to route conflict
        php artisan view:cache

    - name: Run Database Migration
      run: php artisan migrate --force

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jokotingkir-dshcagcgb4fnb2dw'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_31307FC8123F4BC18E9D6E02B8899360 }}
        package: .
