name: Deploy Laravel to Azure Web App - LuaranApp

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, bcmath, curl, gd, xml, zip
          tools: composer:v2
          coverage: none

      - name: Install Composer deps (no-dev) + cache
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          php artisan config:cache
          php artisan view:cache
        # SENGAJA: skip route:cache saat awal

      # Jika kamu TIDAK ingin commit file Nginx 'default' ke repo,
      # kita generate di CI dan ikutkan ke paket:
      - name: Add Nginx config (serve /public)
        run: |
          cat > default <<'NGINX'
          server {
              listen 8080;
              root /home/site/wwwroot/public;
              index index.php index.html;

              location / {
                  try_files $uri $uri/ /index.php?$query_string;
              }

              location ~ \.php$ {
                  include fastcgi_params;
                  fastcgi_pass 127.0.0.1:9000;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  fastcgi_index index.php;
              }

              location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|woff2?|ttf|eot|ico)$ {
                  try_files $uri =404;
                  expires 1y;
                  add_header Cache-Control "public, immutable";
              }
          }
          NGINX

      - name: Fix permissions (safe)
        run: chmod -R 775 storage bootstrap/cache || true

      - name: Create deploy zip
        run: |
          rm -rf .git
          zip -r app.zip . -x "vendor/bin/phpunit" ".github/*"

      - uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-zip

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F0C83C80DCD4ED38E14D586E65705AA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9CAAB9BA4BB24D76A715812C4B532BC9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_04CD588BC5F740D2BFCD64C01D566CD1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LuaranApp'
          slot-name: 'Production'
          package: app.zip

      # (Opsional tapi enak) set Startup Command dari pipeline
      # *** Ganti RG_NAME sesuai punyamu (mis. test-face) ***
      - name: Set Startup Command to point Nginx to /public
        run: |
          az webapp config set \
            --resource-group test-face \
            --name LuaranApp \
            --startup-file "cp /home/site/wwwroot/default /etc/nginx/sites-available/default && service nginx reload"
