# Temporary version - skip route cache to avoid conflicts
name: Build and deploy PHP app to Azure Web App - LuaranApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, bcmath, pdo, mysql, curl, zip
          tools: composer:v2
          
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader --no-interaction
        
      - name: Create production environment file
        run: |
          cat > .env << 'EOF'
          APP_NAME=LuaranApp
          APP_ENV=production
          APP_KEY=
          APP_DEBUG=false
          APP_URL=https://luaranapp-b6ftembfh3hae0hs.canadacentral-01.azurewebsites.net
          
          LOG_CHANNEL=stack
          LOG_LEVEL=error
          
          DB_CONNECTION=mysql
          DB_HOST=luaran-server.mysql.database.azure.com
          DB_PORT=3306
          DB_DATABASE=luaran-database
          DB_USERNAME=flyxgjjjhb
          DB_PASSWORD=$cAuhfFyLzTk$OM2
          
          SESSION_DRIVER=database
          CACHE_STORE=database
          QUEUE_CONNECTION=database
          
          MAIL_MAILER=log
          MAIL_FROM_ADDRESS="hello@luaranapp.com"
          MAIL_FROM_NAME="${APP_NAME}"
          EOF
          
      - name: Generate application key
        run: php artisan key:generate
        
      - name: Directory permissions
        run: chmod -R 755 storage bootstrap/cache
        
      - name: Basic optimization only
        run: |
          php artisan config:cache
          php artisan view:cache
          # Skip route:cache and event:cache to avoid conflicts
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F0C83C80DCD4ED38E14D586E65705AA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9CAAB9BA4BB24D76A715812C4B532BC9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_04CD588BC5F740D2BFCD64C01D566CD1 }}
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'LuaranApp'
          slot-name: 'Production'
          package: .
